#!/usr/bin/python3

import sys
import sympy


def factor(num):
    factors = sympy.factorint(num)

    num1 = min(factors.keys())
    num2 = num // num1

    if num2 > num1:
        num1, num2 = num2, num1

    print(f"{num}={num1}*{num2}")


if len(sys.argv) != 2:
    print("Usage: factors <file>")
    exit(1)
try:
    with open(sys.argv[1], "r") as file:
        while True:
            line = file.readline()
            if not line:
                break
            line = int(line)
            factor(line)
except FileNotFoundError:
    print("Error: File not found.")
    sys.exit(1)
except Exception as e:
    print("An error occurred:", e)
    sys.exit(1)
